CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
name text NOT NULL CHECK (name <> ''),
done BOOLEAN,
projectId INTEGER REFERENCES projects(id) 
);

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES('Make a Web App', 1, 'Using JavaScript', '2020-08-20');

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES('Make an App', 1, 'Using Dart', '2020-08-22'); 

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES('Make a Desktop App', 2, 'Using C++', '2020-08-24'); 

-- INSERT TASK DATA

INSERT INTO tasks(name, done, projectID)
    VALUES('download Vuejs',false, 1);

INSERT INTO tasks(name, done, projectID)
    VALUES('Create UI WEB',false, 1);

INSERT INTO tasks(name, done, projectID)
    VALUES('download Flutter',false, 2);

INSERT INTO tasks(name, done, projectID)
    VALUES('Design UI',false, 2);